version: '3.7'

services:
   java:
      image: java-image
      container_name: java
      volumes:
         - elms-war:/elms-war
         - ./elms:/elms
      build: .
      # uncomment these to make the container persist after the build
      # stdin_open: true
      # tty: true
   tomcat:
      image: tomcat-image
      container_name: tomcat
      build:
         context: .
         dockerfile: ./tomcat/Dockerfile
      ports:
         - 8080:8080
      volumes:
         - elms-war:/elms-war
         - ./document_templates:/document_templates
   #    stdin_open: true
   #    tty: true
volumes:
   elms-war: